name: Deploy Django to Azure Web App

on:
  push:
    branches:
      - master  # Trigger deployment when pushing to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'test-api-apim-v3'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
